### ISSUE TITLE
The db docker is slow for running making the api fail to connect to it

### ISSUE THREAD

**Issue by assem-ch** [assem-ch/namshi-code-challenge#1]

**Comment by ahimta** [comment]
You need to have your app-server image `depends_on` the DB image in `docker-compose.yml` and you don't need to expose the port of the DB image too:sweat_smile:. I'd recommend you read up more on Docker Compose and look at their samples/examples:sweat_smile:. And it may be better too to not use a minimal Node image for development like alpine:sweat_smile:.
